### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by dflock** [Wayn0/geany-dark-scheme#26]
I haven't used Geany in several years and this theme has long gone unmaintained.

There are several open bugs that should be fixed and several forks that should either be incorporated, or switched over to.

I am looking for someone who'd like to take over maintenance of this theme. If you're a Geany user, you use this theme and you'd like to take it over and fix it up - let me know!

**Comment by Wayn0** [comment]
If you still looking, I'll take it.

**Comment by dflock** [comment]
Yay! As soon as I'm near a computer I'll transfer ownership of the repo to you 😀

**Comment by Wayn0** [comment]
I missed the day's grace to accept the invite :( been a bit ill.

**Comment by dflock** [comment]
OK, I've aborted & re-started the transfer.

**Comment by Wayn0** [comment]
Thanks, it's done. I'll start giving this some attention soon
