### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by dllud** [Wayn0/geany-dark-scheme#27]
Could you please [choose a license](https://choosealicense.com/) and add it to the repo?

I've just noticed that this project lacks license info. As it stands it is covered by copyright and no-one is rightfully allowed to fork or modify it.

**Comment by dflock** [comment]
If you would like to take this project over, rather than creating confusion by forking it, please just let me know - I can transfer the repo to you.

https://github.com/dflock/geany-dark-scheme/issues/26

**Comment by dllud** [comment]
Thanks, but right now I feel I can bring nothing new to this project.
I just forked it to change a few colours, making it suit a Dark GTK Theme I use: [Candra-Themes-3.20](https://github.com/dllud/Candra-Themes-3.20). I added no new features.
